/**
 * Maps ISO language codes to human-readable language names with region codes
 */
export const LANGUAGE_MAP = {
    en: 'English (US)',
    eng: 'English (US)',
    enUS: 'English (US)',
    'en-US': 'English (US)',
    'en-GB': 'English (UK)',
    enGB: 'English (UK)',
    ko: 'Korean (KR)',
    kor: 'Korean (KR)',
    es: 'Spanish (ES)',
    spa: 'Spanish (ES)',
    'es-419': 'Spanish (Latin America)',
    'es-LA': 'Spanish (Latin America)',
    esLA: 'Spanish (Latin America)',
    fr: 'French (FR)',
    fra: 'French (FR)',
    fre: 'French (FR)',
    'fr-CA': 'French (CA)',
    frCA: 'French (CA)',
    de: 'German (DE)',
    deu: 'German (DE)',
    ger: 'German (DE)',
    it: 'Italian (IT)',
    ita: 'Italian (IT)',
    ja: 'Japanese (JP)',
    jpn: 'Japanese (JP)',
    zh: 'Chinese (Simplified)',
    zho: 'Chinese (Simplified)',
    chi: 'Chinese (Simplified)',
    'zh-TW': 'Chinese (Traditional)',
    zhTW: 'Chinese (Traditional)',
    pt: 'Portuguese (PT)',
    por: 'Portuguese (PT)',
    'pt-BR': 'Portuguese (BR)',
    ptBR: 'Portuguese (BR)',
    ru: 'Russian (RU)',
    rus: 'Russian (RU)',
    ar: 'Arabic (001)',
    ara: 'Arabic (001)',
    hi: 'Hindi (IN)',
    hin: 'Hindi (IN)',
    tr: 'Turkish (TR)',
    tur: 'Turkish (TR)',
    nl: 'Dutch (NL)',
    nld: 'Dutch (NL)',
    dut: 'Dutch (NL)',
    sv: 'Swedish (SE)',
    swe: 'Swedish (SE)',
    no: 'Norwegian Bokmal (NO)',
    nor: 'Norwegian Bokmal (NO)',
    fi: 'Finnish (FI)',
    fin: 'Finnish (FI)',
    da: 'Danish (DK)',
    dan: 'Danish (DK)',
    pl: 'Polish (PL)',
    pol: 'Polish (PL)',
    hu: 'Hungarian (HU)',
    hun: 'Hungarian (HU)',
    cs: 'Czech (CZ)',
    ces: 'Czech (CZ)',
    cze: 'Czech (CZ)',
    el: 'Greek (GR)',
    ell: 'Greek (GR)',
    gre: 'Greek (GR)',
    he: 'Hebrew (IL)',
    heb: 'Hebrew (IL)',
    ro: 'Romanian (RO)',
    ron: 'Romanian (RO)',
    rum: 'Romanian (RO)',
    th: 'Thai (TH)',
    tha: 'Thai (TH)',
    id: 'Indonesian (ID)',
    ind: 'Indonesian (ID)',
    ms: 'Malay (MY)',
    msa: 'Malay (MY)',
    may: 'Malay (MY)',
    vi: 'Vietnamese (VN)',
    vie: 'Vietnamese (VN)',
    tl: 'Filipino (PH)',
    fil: 'Filipino (PH)',
    uk: 'Ukrainian (UA)',
    ukr: 'Ukrainian (UA)',
    hr: 'Croatian (HR)',
    hrv: 'Croatian (HR)',
    sk: 'Slovak (SK)',
    slk: 'Slovak (SK)',
    slo: 'Slovak (SK)'
  };
  
  /**
   * Muxed By
   */
  export const COMMON_MUXER = 'Ionicboy';